# Generated by Django 3.1.1 on 2022-04-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('sport', 'SPORT'), ('culture', 'CULTURE'), ('news', 'NEWS'), ('gossip', 'GOSSIP'), ('philosophy', 'PHILOSOPHY'), ('history', 'HISTORY'), ('women_history', 'WOMEN_HISTORY')], default='', max_length=20),
        ),
    ]
